
function deepnet=FiveAE(xTrainImages,hiddenUnitNumbers,pretrainingIterations,fineTuningIterations,tTrain1, tTrain)

hiddenSize1 = hiddenUnitNumbers;
autoenc1 = trainAutoencoder(xTrainImages,hiddenSize1, ...
    'MaxEpochs',pretrainingIterations, ...
    'L2WeightRegularization',0.004, ...
    'SparsityRegularization',2, ...
    'SparsityProportion',0.8, ...
    'ScaleData', true);

feat1 = encode(autoenc1,xTrainImages);
%%

%SECOND AE
hiddenSize2 = hiddenUnitNumbers;
autoenc2 = trainAutoencoder(feat1,hiddenSize2, ...
    'MaxEpochs',pretrainingIterations, ...
    'L2WeightRegularization',0.002, ...
    'SparsityRegularization',2, ...
    'SparsityProportion',0.85, ...
    'ScaleData', true);
feat2 = encode(autoenc2,feat1);
%%
%THIRD AE
hiddenSize3 = hiddenUnitNumbers;
autoenc3 = trainAutoencoder(feat2,hiddenSize3, ...
    'MaxEpochs',pretrainingIterations, ...
    'L2WeightRegularization',0.002, ...
    'SparsityRegularization',2, ...
    'SparsityProportion',0.85, ...
    'ScaleData', true);
feat3 = encode(autoenc3,feat2);

%%
%FORTH AE
hiddenSize4 = hiddenUnitNumbers;
autoenc4 = trainAutoencoder(feat3,hiddenSize4, ...
    'MaxEpochs',pretrainingIterations, ...
    'L2WeightRegularization',0.002, ...
    'SparsityRegularization',2, ...
    'SparsityProportion',0.85, ...
    'ScaleData', true);
feat4 = encode(autoenc4,feat3);
%%
%FIFTH AE
hiddenSize5 = hiddenUnitNumbers;
autoenc5 = trainAutoencoder(feat4,hiddenSize5, ...
    'MaxEpochs',pretrainingIterations, ...
    'L2WeightRegularization',0.002, ...
    'SparsityRegularization',2, ...
    'SparsityProportion',0.85, ...
    'ScaleData', true);
feat5 = encode(autoenc5,feat4);
softnet = trainSoftmaxLayer(feat5,tTrain1,'MaxEpochs',fineTuningIterations);
deepnet = stack(autoenc1,autoenc2,autoenc3,autoenc4,autoenc5,softnet);

deepnet = train(deepnet,xTrainImages,tTrain);