function deepnet=TwoAE(xTrainImages,hiddenUnitNumbers,pretrainingIterations,fineTuningIterations,tTrain1, tTrain);

hiddenSize1 = hiddenUnitNumbers;
autoenc1 = trainAutoencoder(xTrainImages,hiddenSize1, ...
    'MaxEpochs',pretrainingIterations, ...
    'L2WeightRegularization',0.004, ...
    'SparsityRegularization',2, ...
    'SparsityProportion',0.8, ...
    'ScaleData', true);

feat1 = encode(autoenc1,xTrainImages);

%%
%SECOND AE
hiddenSize2 = hiddenUnitNumbers;
autoenc2 = trainAutoencoder(feat1,hiddenSize2, ...
    'MaxEpochs',pretrainingIterations, ...
    'L2WeightRegularization',0.002, ...
    'SparsityRegularization',2, ...
    'SparsityProportion',0.85, ...
    'ScaleData', true);
% view(autoenc2)
feat2 = encode(autoenc2,feat1);

%%
softnet = trainSoftmaxLayer(feat2,tTrain1,'MaxEpochs',fineTuningIterations);
% view(softnet)
%%
deepnet = stack(autoenc1,autoenc2,softnet);

deepnet = train(deepnet,xTrainImages,tTrain);